- hosts: '123'
  gather_facts: false
  become_user: root
  become: true
#  vars_files:
#    - ../group_vars/vars
  tasks:
    - name: copy the nginx conf to the remote machine
      copy:
        src=nginx.conf dest=/tmp/
    - name: run nginx container
      shell:
        docker run --detach   --name ucp-lb   --restart=unless-stopped   --publish 443:443 -p 80:80 -v /tmp/nginx.conf:/etc/nginx/nginx.conf:ro   nginx:stable-alpine 
