- name: copy the ucp license to the remote machine
  copy:
    src=docker_subscription.lic dest=/tmp/

- name: download and install ucp images
  shell:
    docker run --rm  --name ucp -v /var/run/docker.sock:/var/run/docker.sock docker/ucp:{{ UCP_Version }} install --host-address {{ UCP_Manager_IP }}  --admin-username {{ UCP_Admin }} --admin-password {{ UCP_Admin_Pass }} --san {{ UCP_San }} --license "$(cat /tmp/docker_subscription.lic)"
  when: inventory_hostname in groups.ucp-main
- name: capture swarm join token - manager
  shell:
    echo `docker swarm join-token manager` | cut -f2 -d':' | sed 's|\\||g'
  register: managertoken
  when: inventory_hostname in groups.ucp-main
- name: capture swarm join token - worker
  shell:
    echo `docker swarm join-token worker` | cut -f2 -d':' | sed 's|\\||g'
  register: worktoken
  when: inventory_hostname in groups.ucp-main
- name: save managertoken
  local_action: copy content="token{{ ":" }} {{ hostvars[groups['UCP-manager'][0]]['managertoken']['stdout'] }}" dest=/tmp/manager_token

- name: save worktoken
  local_action: copy content="token{{ ":" }} {{ hostvars[groups['UCP-manager'][0]]['worktoken']['stdout'] }}" dest=/tmp/worker_token

- name: Get manager token
  include_vars:
    file: /tmp/manager_token
    name: add_manager
- name: Add manager nodes to the swarm
  command: "{{ add_manager.token }}"
  when: inventory_hostname not in groups.ucp-main
